services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: helpmelearn
      MYSQL_USER: user
      MYSQL_PASSWORD: password@123
    ports:
      - "3306:3306"
    expose:
      - '3306'
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
